### ISSUE TITLE
Where's requirements.txt?

### ISSUE THREAD

**Issue by lallousx86** [IDAConnect/IDAConnect#4]
Hello,

I wanted to try the plugin but the instructions are incomplete.

Where's the 'plugin' folder and where are requirements.txt ?

**Comment by NeatMonster** [comment]
Hello there. I'm sorry, you came just in the middle of a big refactoring to remove the dependency on Twisted. I pushed some of my code late at night and haven't had time to update the instructions yet.

Quick fix: use the code at eb8035cded23ff6d2876d338fab673f7f5141c81. The dependencies of the plugin were `twisted`, `qt5reactor`, and `pypiwin32`on Windows, while the server depended only on `twisted`.

Otherwise, once I'm done removing Twisted (hopefully soon), no more dependency installation will be needed. That means that you should be able to run the server separately (dedicated) or right into IDA (integrated). It also means that we can make an easy installation script so that you only need to copy-paste a one liner into IDA to install the plugin. The server will require `PyQt5` which can be installed with`pip` on Python 3 (which is way I made sure the code is now Python 2 and 3 compatible).

I will keep this issue open until the refactoring is done. Thanks @lallousx86 for the heads up!

**Comment by NeatMonster** [comment]
@lallousx86 The `README.md` has been updated, I think I can now close this issue.
